name: nf-encyclopedia
channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - python=3.10
  - pytest
  - numpy
  - pandas
  - bioconda::bioconductor-msstats
  - conda-forge::r-rlang
  - conda-forge::r-dplyr
  - conda-forge::r-tidyr
  - r::r-magrittr
  - r::r-stringr
