site_name: nf-encyclopedia
repo_url: https://github.com/TalusBio/nf-encyclopedia
nav:
  - Home: index.md
  - Parameters: parameters.md
  - Cite: CITATION.md

theme:
  name: material
  favicon: static/talus-logo.svg
  logo: static/talus-logo.svg
  font:
    text: IBM Plex Sans
  features:
     - toc.integrate
     - navigation.tabs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - smarty
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/talusbio

plugins:
  - search
