contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #encyclopedia channel"
    url: https://nfcore.slack.com/channels/encyclopedia
    about: Discussion about the nf-core/encyclopedia pipeline
