name: Push docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install font
        run: |
          cd /usr/share/fonts
          wget https://github.com/JulietaUla/Montserrat/archive/refs/tags/v7.222.tar.gz
          tar -xvzf v7.222.tar.gz
          sudo chmod -R --reference=/usr/share/fonts/truetype Montserrat-7.222
          sudo fc-cache -fv
          fc-match Montserrat

      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force
