name: Release Nextflow Workflow

on: 
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create latest tag
        uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
